#!/bin/bash
# Puesta en marcha del servidor
echo "Instalando componentes"
sudo apt-get install ssh
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
sudo apt-get update
sudo apt-get install -y mongodb-org
sudo apt-get install python-dev
#sudo apt-get install python-pip
sudo apt-get install python-virtualenv
sudo apt-get update
sudo apt-get upgrade

sudo mkdir practica_1
cd practica_1
sudo virtualenv flask
sudo . flask/bin/activate
pip install -r requirements.txt

